### ISSUE TITLE
Why  i got Nan when i train the ncsnpp?

### ISSUE THREAD

**Issue by manmushanhe** [sp-uhh/sgmse#30]
I change the nfft to 510, and backbone to ncsnpp, but i got nan in the training. Could you help me ?

**Comment by zoupengpeng128** [comment]
> I change the nfft to 510, and backbone to ncsnpp, but i got nan in the training. Could you help me ?

I have the same problem. Have you solved it?

**Comment by julius-richter** [comment]
We have never encountered a problem like this before. Maybe it has something to do with the internal precision of matrix multiplications in PyTorch.

In any case, we have just updated the code to PyTorch 2.X and Lightning 2.X to ensure support for newer GPUs. Try running the code again after you have created a virtual environment with the new requirements.

**Comment by Respaired** [comment]
the 48khz config gives me nan on torch 2.X 
unless it has something to do with my dataset which i have a hard time to figure out why, this issues still persists.

**Comment by julius-richter** [comment]
Can you please specify your training command and the dataset you are using?

**Comment by Respaired** [comment]
> Can you please specify your training command and the dataset you are using?

Sure, thanks for the quick response btw, i appreciate it.

i used the exact same command for the 48khz you posted on the repo which is ```--backbone ncsnpp_48k --n_fft 1534 --hop_length 384 --spec_factor 0.065 --spec_abs_exponent 0.667 --sigma-min 0.1 --sigma-max 1.0 --theta 2.0``` + using -1 for the gpus to use every available devices i have and also 10,000 steps for saving ckpts. the training starts with no issue but 100 steps in it throws nan. the loss is also very lare somewhere in the ballpark of 3e+4 which starts to go down but suddenly goes nan.

my dataset is a 48khz Japanese corpus the noisy ones were corrupted by the Mp3Compression (bit rate = between 16 to 32) module of the audiomentations library to simulate the compression artifacts. (it doesn't have any gaussian noise, but the inputs are completely audible and intelligible, so it's nothing crazy). it's around 59,000 samples, less than a 100 hrs.

**Comment by julius-richter** [comment]
Looks all fine. It could be that you get a NaN in the data_loader. This could happen, for example, in the normalization of the time domain signal. Could you try to add a small eps to the denominator in line 86 and 87: https://github.com/sp-uhh/sgmse/blob/main/sgmse/data_module.py#L86

**Comment by Respaired** [comment]
np. i'll try that when my cluster is free, it'll take a while. I'll respond back to this thread when i do.

**Comment by Respaired** [comment]
very well, that does seem to have done the trick. i finished training a model on the 16khz and ncsnpp_v2. but the 48khz now throws another error : 

```RuntimeError: stack expects each tensor to be equal size, but got [1, 768, 256] at entry 0 and [1, 768, 273] at entry 4 ```

any idea on how to tackle this? though 16khz was a solid run (with a pesq of 3.47) but 16khz is just useless.

**Comment by julius-richter** [comment]
The error message points to an issue with creating a batch in the `collate_fn` of the dataloader. The last dimension represents the time dimension of the spectrogram. The tensors should all have the same shape by default in the dataloader. You can refer to the specific implementation here: https://github.com/sp-uhh/sgmse/blob/main/sgmse/data_module.py#L71

Could you please provide the complete error stack?

**Comment by Respaired** [comment]
yeah i figured as such. sounds like it doesn't take too kindly to samples shorter than 2 seconds long.
i managed to finish a few epochs by removing those. but the PESQ is around 1.13 so i'm gonna give up on 48khz at this point.
thanks

**Comment by sui-studio** [comment]
awesome, this was helpful!
